# Step 1: import the library
### In this step we will import the libraries we will need:
- **pandas**: to load the data, which is a library that provides high flexibility in dealing with and loading tabular data (**DataFrame**).
- **Matplotlib**: We used matplotlib library because it provides various charting tools and is the most widely used for visualization.
- **Pickle**: We use pickle so that we can work with files having the .pkl extension.
- **Sklearn.linear_model**: to use the linear model we need (*in our case, __LinearRegression__, __Ridge__, __Lasso__*).
- **Sklearn.ensemble**: to use the __RandomForestRegressor__ model.
- **Sklearn.matrics**: to use the model evaluation tools we need (*in our case, __r2_score__*).
- **Sklearn.model_selection**: to use the tools for developing and selecting models (*in our case, __train_test_split__ to split data, and __gridsearchcv__ to find the best parameter for the model*).
### The links:
- **[Scikit-learn](https://scikit-learn.org/stable/)**
- **[Pandas](https://pandas.pydata.org/)**
- **[Matplotlib](https://matplotlib.org/)**

In [18]:
import pandas as pd # to loading data
import matplotlib.pyplot as plt # for visualization
import pickle
from sklearn.linear_model import LinearRegression, Ridge, Lasso # to use the linear model we need
from sklearn.ensemble import RandomForestRegressor # to use the RandomForestRegressor
from sklearn.metrics import r2_score # to evalueation the models
from sklearn.model_selection import GridSearchCV # to find the parameter for the models
from sklearn.model_selection import train_test_split # to split the data

# Step 2: load the data
### In this step we will load tabular data from boston.csv file using pandas which is table with this features:
- `CRIM`: per capita crime rate by town
- `ZN`: proportion of residential land zoned for lots over 25,000 sq.ft.
- `INDUS`: proportion of non-retail business acres per town
- `CHAS`: Charles River dummy variable (1 if tract bounds river; 0 otherwise)
- `NOX`: nitric oxides concentration (parts per 10 million) [parts/10M]
- `RM`: average number of rooms per dwelling
- `AGE`: proportion of owner-occupied units built prior to 1940
- `DIS`: weighted distances to five Boston employment centres
- `RAD`: index of accessibility to radial highways
- `TAX`: full-value property-tax rate per $10,000 [$/10k]
- `PTRATIO`: pupil-teacher ratio by town
- `B`: The result of the equation B=1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town (*this column will be removed because it expresses racial variables, which is considered illogical and racist.*)
- `LSTAT`: % lower status of the population.

### And the target:
- `MEDV`: the price of the houce

In [19]:
data = pd.read_csv("boston.csv") # loading data from boston.csv file
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [21]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

# Step 3: drop and remove the are not afraid of it
### In this step we remove this features (*columns*):
 1) **CHAS**: Because it is correlation with price is weak. (*We will know this in the next codes.*)
 2) **B**: Becouse it is illogical and racist.

In [22]:
correlation = data.corr().loc[["MEDV"]] # find the correlation 
correlation

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
MEDV,-0.388305,0.360445,-0.483725,0.17526,-0.427321,0.69536,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.0

In [23]:
data.drop(["CHAS", "B"], axis=1, inplace=True)

# Step 4: spliting the data
### To train our model, we need to split the data into training and testing sets.  

- **X**: The features (independent variables) used to make predictions.  
- **y**: The target variable (what we want to predict).
```python
X = data.drop("MEDV", axis=1)
y = data["MEDV"]
```

- **X_train**: 80% of `X`, used to train the model.  
- **X_test**: 20% of `X`, used to evaluate the model.  
- **y_train**: Corresponding 80% of `y`, for training.  
- **y_test**: Corresponding 20% of `y`, for evaluation.  

### We use `train_test_split` from `sklearn` to split the data:
```python
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
X = data.drop("MEDV", axis=1) # this mean X = All features except MEDV
y = data["MEDV"] # and y = the target MEDV

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33) # spliting the data

# Step 5: try try the models and choose the best one
### In this step we will:
1. Train each models using `X_train` and `y_train`
2. Testing the models using `X_test` and `y_test`
4. Evaluation the models using `r2_score` (*The higher the __r2_score number__, the better.*)
5. Choose the best model

In [26]:
def model_trying(model_dic, X_train, X_test, y_train, y_test):
    models_details = {}
    for model_name, model in model_dic.items():
        model.fit(X_train, y_train) # model training
        y_pred = model.predict(X_test) # Predicting model results
        r2_score_model = r2_score(y_test, y_pred) # return the r2 score number
        models_details[model_name.replace("_", " ")] = {
            "model": model, # save the model
            "r2_score": r2_score_model # sabe the model's r2 score
        }
    return models_details

In [27]:
models = {
    'Linear Regression': LinearRegression(fit_intercept=True),
    'Ridge Regression': Ridge(alpha=1.0, fit_intercept=True),
    'Lasso Regression': Lasso(alpha=0.1, fit_intercept=True),
    'Random Forest': RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
}

In [28]:
result = model_trying(models, X_train, X_test, y_train, y_test)
result

{'Linear Regression': {'model': LinearRegression(),
  'r2_score': 0.682204188548306},
 'Ridge Regression': {'model': Ridge(), 'r2_score': 0.6720123566569233},
 'Lasso Regression': {'model': Lasso(alpha=0.1),
  'r2_score': 0.6552144046038189},
 'Random Forest': {'model': RandomForestRegressor(max_depth=10, random_state=42),
  'r2_score': 0.8285587542444873}}

# Step 6: develop and improve the model
### In the Step 4 we found that the RandomForestRegressor model is the most suitable for our data. (*you can see this in this image*)
<img src="models_r2_score.png" width="500">

### At this stage we will know the best parameters for this model.
### We will use the hyperparameter tuning tool, (*GridSearchCV*)

In [29]:
param_grid = {
    'n_estimators': [i for i in range(50, 200, 10)],         # عدد الأشجار
    'max_depth': [10, 20, None],            # عمق الشجرة
    'min_samples_split': [2, 5, 10],        # عدد العينات المطلوبة لتقسيم العقدة
    'min_samples_leaf': [1, 2, 4],          # عدد العينات المطلوبة في العقدة
}
grid_search = GridSearchCV(estimator=result["Random Forest"]["model"], param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)
print("Best parameters found: ", grid_search.best_params_)

# the best parameters
best_model = grid_search.best_estimator_

# حساب الأداء باستخدام أفضل نموذج
y_pred = best_model.predict(X_test)

Fitting 5 folds for each of 405 candidates, totalling 2025 fits
Best parameters found:  {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 130}

In [33]:
best_model = RandomForestRegressor(max_depth=20, min_samples_leaf=1, min_samples_split=2, n_estimators=130)
best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)

# Step 7: get the finly result
### We will use r2 to calculate the final accuracy as we did before.

In [34]:
RandomForestRegressor_details = {
    "model": best_model,
    "r2_score": r2_score(y_test, y_pred)
}
RandomForestRegressor_details["r2_score"]

0.8262043954042857

# Step 8: save the model and th result
### Save the model and the r2_score in .pkl file, because this extension allows us to save objects
### this means that it is possible to return to the model and the results at a later time.

In [35]:
with open("model_details.pkl", "wb") as file:
    pickle.dump(RandomForestRegressor_details, file)

### (*We can retrieve the model details at any time using the following code.*):
```python
with open("model_details.pkl", "rb") as file:
    RandomForestRegressor_details = pickle.load(file)